cr-org/neutron

src/main/scala/cr/pulsar/Consumer.scala
src/main/scala/cr/pulsar/Publisher.scala
src/main/scala/cr/pulsar/Topic.scala

use FiniteDuration instead of Long for maxDelay
use Topic.URL instead of creating Topic.Name from url for logAction
publish returns MessageID instead of Unit
add a non blocking publishAsync
.. thanks for writing a cool FP book :)

small contribution

---

src/main/scala/cr/pulsar/Consumer.scala
src/main/scala/cr/pulsar/Publisher.scala
src/main/scala/cr/pulsar/Topic.scala

https://pulsar.apache.org/docs/en/concepts-messaging/#multi-topic-subscriptions

Add multi-topic consumer

---

.github/workflows/ci.dhall
.github/workflows/ci.yml
build.sbt
docker-compose.yml
project/Dependencies.scala
src/main/scala/cr/pulsar/Publisher.scala
src/main/scala/cr/pulsar/Subscription.scala
src/test/scala/cr/pulsar/PulsarSpec.scala

- Add `docker-compose.yml` file to run Pulsar locally and in the CI build.
- Add first Pulsar test.
- Add newtype `Subscription.Name` to avoid using a plain String.
- Remove unnecessary `lazy` keyword in the definition of a pure resource.

Add Pulsar integration test

---

build.sbt
project/plugins.sbt
src/main/scala/cr/pulsar/Client.scala
src/main/scala/cr/pulsar/Config.scala
src/main/scala/cr/pulsar/Consumer.scala
src/main/scala/cr/pulsar/Publisher.scala
src/main/scala/cr/pulsar/Subscription.scala
src/main/scala/cr/pulsar/Topic.scala
src/main/scala/cr/pulsar/internal/FutureLift.scala
src/test/scala/cr/pulsar/PulsarSpec.scala

Also adding a list of developers, required by the `sbt-ci-release` plugin when making a release.

Add license headers plugin

---

src/main/scala/cr/pulsar/Publisher.scala
src/test/scala/cr/pulsar/PulsarSpec.scala

https://pulsar.apache.org/docs/en/client-libraries-java/#subscription-modes

Specify message key for key-shared topics

---

src/main/scala/cr/pulsar/Publisher.scala
src/test/scala/cr/pulsar/PulsarSpec.scala
src/test/scala/cr/pulsar/PulsarSuite.scala

Sorry, I screwed up in #26 . A `MessageKey` can only be calculated per message.
I added a proper test to make sure this works.

Add option to publish a message with a key

---

core/src/main/scala/cr/pulsar/Reader.scala

In this PR I have implemented a wrapper for `Reader` interface: https://pulsar.apache.org/docs/en/client-libraries-java/#reader

Implement Reader

---

build.sbt
function/src/main/scala-2.12/cr/pulsar/JavaConversions.scala
function/src/main/scala-2.13/cr/pulsar/JavaConversions.scala
function/src/main/scala/cr/pulsar/Context.scala
function/src/main/scala/cr/pulsar/Function.scala
function/src/main/scala/cr/pulsar/Record.scala
function/src/main/scala/cr/pulsar/WindowContext.scala
function/src/main/scala/cr/pulsar/WindowFunction.scala
function/src/test/scala/cr/pulsar/FunctionInput.scala
function/src/test/scala/cr/pulsar/FunctionSpec.scala
function/src/test/scala/cr/pulsar/WindowContextSpec.scala
function/src/test/scala/cr/pulsar/WindowFunctionSpec.scala
project/Dependencies.scala

Implemented wrapper for `function` module

Add neutron-function module

---

.github/workflows/publish-site.yml
.github/workflows/release.yml
build.sbt
core/src/it/scala/cr/pulsar/PulsarSpec.scala
core/src/main/scala/cr/pulsar/Producer.scala
docs/src/paradox/index.md

Getting rid of the need for `Blocker`.

Fully async producer

---

core/src/it/scala/cr/pulsar/PulsarSpec.scala
core/src/main/scala/cr/pulsar/Consumer.scala
docs/src/paradox/index.md

We have `Producer[F, E]` - parameterised over the message type - but we leak Java's Message type as an `Array[Byte]` in `subscribe`. This PR intends to make it consistent by parameterising `Consumer[F, E]` as well.
Encoding and decoding will now be done both by producers and consumers via the `Inject` instance.

Consumer decodes messages via Inject

---

core/src/main/scala/cr/pulsar/Consumer.scala

The Java documentation says the `unsubscribe` operation will fail when performed on a shared subscription where multiple consumers are currently connected.
Initially, I thought of calling `unsubscribe` only when the subscription type is either `Exclusive` or `Failover` but at some point we want the unsubscription to take effect (when there is one last consumer calling it). So I chose to go with calling it always and ignore any possible errors via `attempt.void`.
https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L60

Fix unsubscribe call

---

.github/workflows/publish-site.yml
.github/workflows/release.yml
shell.nix

Apparently all that action does is installing `gnupg` so we might as well use Nix: https://github.com/olafurpg/setup-gpg/blob/master/src/main.ts

Setup gnupg using nix

---

.github/workflows/ci.yml

https://github.com/marketplace/actions/sbt-coursier-cache

Add sbt-coursier-cache action

---

.github/workflows/ci.yml

https://github.com/marketplace/actions/coursier-cache-action

Official coursier cache action

---

.github/workflows/ci.yml
.github/workflows/publish-site.yml
.github/workflows/release.yml
.github/workflows/sbt-nix.yml
.gitignore
pkgs.nix
sbt.nix
shell.nix

This should dramatically improve the CI build times :crossed_fingers:

Use Cachix for sbt derivations

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

https://github.com/marketplace/actions/release-drafter

Set up release drafter

---

core/src/main/scala/cr/pulsar/Reader.scala

Rename current `Reader` as `MessageReader` and introduce a new `Reader` that operates only over its `payload`.

Rework Reader interface

---

circe/src/main/scala/cr/pulsar/schema/circe/AutoDerivation.scala
circe/src/main/scala/cr/pulsar/schema/circe/JsonSchema.scala
docs/src/paradox/index.md
tests/src/it/scala/cr/pulsar/domain/Event.scala
tests/src/it/scala/cr/pulsar/domain/Event_V2.scala
tests/src/it/scala/cr/pulsar/domain/Event_V3.scala
tests/src/it/scala/cr/pulsar/domain/Fruit.scala
tests/src/it/scala/cr/pulsar/domain/Outer.scala

Basically improving usage by avoiding the extra `com.sksamuel.avro4s.AvroSchema` import.

JsonSchema derivation via avro4s

---

project/Dependencies.scala

Update cats-effect to 2.4.1

---

tests/src/it/scala/cr/pulsar/AlwaysIncompatibleSchemaSuite.scala

This import blocks updates coming from `scala-steward`

Remove unused import

---

docs/src/paradox/index.md
project/Dependencies.scala
tests/src/it/scala/cr/pulsar/AlwaysIncompatibleSchemaSuite.scala

closes #252 
closes #249 
closes #248

fix updates of ce, fs2 & weaver
